import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import PrivacyPolicy from "./privacy_policy/page";
import "./globals.css";
import Navbar from "../../componenets/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        {children}
      <footer className="bg-white border-t border-gray-200 px-4 py-4 mt-8 w-full">
        <div className="flex flex-wrap justify-center mb-4 space-x-4">
          <a href="/" className="text-gray-700 hover:text-green-600 font-medium px-3 py-2 rounded transition">Home</a>
          <a href="/about" className="text-gray-700 hover:text-green-600 font-medium px-3 py-2 rounded transition">About</a>
          <a href="/generate" className="text-gray-700 hover:text-green-600 font-medium px-3 py-2 rounded transition">Generate Recipe</a>
          <a href="/feedback" className="text-gray-700 hover:text-green-600 font-medium px-3 py-2 rounded transition">Feedback</a>
        </div>
        <div className="flex flex-col md:flex-row items-center justify-between">
          <span className="text-gray-600 text-sm mb-2 md:mb-0">
            &copy; {new Date().getFullYear()} Recipe Generator. All rights reserved.
          </span>
          <div className="flex space-x-4">
            <a href="/privacy_policy" className="text-gray-500 hover:text-green-600 text-sm transition">
              Privacy Policy
            </a>
            <a href="/terms_service" className="text-gray-500 hover:text-green-600 text-sm transition">Terms of Service</a>
            <a href="/contact" className="text-gray-500 hover:text-green-600 text-sm transition">Contact</a>
          </div>
        </div>
      </footer>
      </body>
    </html>
  );
}
